---
kind: Service
apiVersion: v1
metadata:
  name: palo-fe-service
  namespace: ns-palo
  labels:
    app: palo
    role: fe
spec:
  ports:
    - port: 8030
      name: http-port
    - port: 9020
      name: rpc-port
    - port: 9030
      name: query-port
    - port: 9010
      name: edit-log-port
  selector:
    app: palo
    role: fe
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-palo-fe
  namespace: ns-palo
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data3/palo-fe"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-claim-palo-fe
  namespace: ns-palo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: palo-fe
  namespace: ns-palo
  labels:
    app: palo
    role: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: palo
  serviceName: palo-fe-service
  template:
    metadata:
      labels:
        app: palo
        role: fe
    spec:
      volumes:
        - name: pv-storage-palo-fe
          persistentVolumeClaim:
            claimName: pv-claim-palo-fe
      containers:
        - name: palo-fe
          image: palo-fe:v0.9.21-3.4
          command: ["bash", "-c", "exec docker-entrypoint.sh"]
          ports:
            - containerPort: 8030
              protocol: TCP
            - containerPort: 9020
              protocol: TCP
            - containerPort: 9030
              protocol: TCP
            - containerPort: 9010
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/palo/fe/palo-meta
              name: pv-storage-palo-fe
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: palo
  name: palo-fe-web-service
  namespace: ns-palo
spec:
  type: NodePort
  ports:
    - port: 8030
      targetPort: 8030
      nodePort: 28030
  selector:
    app: palo
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: palo
  name: palo-fe-query-service
  namespace: ns-palo
spec:
  type: NodePort
  ports:
    - port: 9030
      targetPort: 9030
      nodePort: 29030
  selector:
    app: palo
